from fastapi import FastAPI
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


  
app = FastAPI()
  
port = 2525
smtp_server = "smtp.mailmug.net"
login = "fpjddvsctbxrtfzz" # paste your login generated by mailmug
password = "ww9m7avdxzdgjuge" # paste your password generated by mailmug
  
sender_email = "mailmug@example.com"
receiver_email = "new@example.com"
message = MIMEMultipart("alternative")
message["Subject"] = "Test subject"
message["From"] = sender_email
message["To"] = receiver_email
  
  
@app.get("/send-email")
def send_email():
     # write the HTML part
    html = """\
        <html>
        <body>
            <p>Hi,<br>
            This is the test email</p>
        </body>
        </html>
        """
    part = MIMEText(html, "html")
    message.attach(part)
  
    server = smtplib.SMTP(smtp_server, port)
    server.set_debuglevel(1)
    server.esmtp_features['auth'] = 'LOGIN DIGEST-MD5 PLAIN'
    server.login(login, password)
    server.sendmail(
        sender_email, receiver_email, message.as_string()
    )

    return {"msg":"send mail"}